docker-storage-setup.1
docker-storage-setup.sh

This pull request contains changes for support of setting up lvm thin pool for docker consumption.
I have opened following issue.
https://github.com/projectatomic/docker-storage-setup/issues/3
This is not default right now and one will have to set SETUP_LVM_THIN_POOL=yes in /etc/sysconfig/docker-storage-setup for new code to kick in. 
Please review and pull.

Lvm thin pool setup

---

docker-storage-setup.sh

This fixes issue #10 
By default docker sets up a thin pool where block zeroing is skipped. This
script basically sets up a pool for docker, so use same behavior.
In general thin pool folks have recommended using skip block zeroing. 

docker-storage-setup: Skip block zeroing in thin pool

---

docker-storage-setup.sh

Fixes issue #13 
Right now docker-storage-setup keeps on extending the size of data volume
as long as there is free space in the pool. So even if a user has left
some space in the pool free for metadata volume extension, that free space
will be consumed by data volume extension.
Now lvm2 has nice capabilities to automatically extend pool (both data and
metadata) when pool is running short on space. Following are two knobs which
one can use for auto extension.
thin_pool_autoextend_threshold = 100
thin_pool_autoextend_percent = 20
By default extension is disabled. One needs to enable it manually by chaning
the value of thin_pool_autoextend_threshold.
In general it is a good idea to know consume all the free pool space until
and use mechanism like extending pool by certain percentage when it …

docker-storage-setup: Disable auto extension of data logical volume

---

docker-storage-setup.1
docker-storage-setup.sh

Fixes issue #12 
Docker does not do all the error handing which can be required if thin
pool gets full or thin pool runs into issues. So passing block devices
to docker and let it setup thin pool is not a very good idea from error
handling point of view.
Instead always setup lvm thin pool and pass that to docker so that docker
does not have to take care of pool management issues and lvm2 commands
can take care of it. (See man lvmthin).

Remove old data and metadata volume mode support

---

docker-storage-setup.sh

This fixes issue #16 
Right now upon each run of script, we overwrite /etc/sysconfig/docker-storage
and this could be bad if user added some of his own storage options. These
will be lost over next run of script.
Write /etc/sysconfig/docker-storage only when pool is created. After that
leave it untouched.

docker-storage-setup: Do not overwrite /etc/sysconfig/docker-storage always

---

docker-storage-setup.sh

Just noticed this while reviewing another PR; previously if we got
e.g. ENOSPC or something on startup, we'd leave a broken partially
written file.  Do the tempfile + `rename()` dance.

Atomically update config file

---

docker-storage-setup.conf
docker-storage-setup.spec

Fixes issue #18 
I think sending a documented default config file with the package makes it
easy to configure and makes it easy to more config options down the line,
like chunk size of thin pool.

docker-storage-setup: Create a default config file to be shipped with pkg

---

docker-storage-setup.1
docker-storage-setup.sh

Fixes issue #21   
If DATA_SIZE is specified we will auto grow data volume if there is free
space in pool. Say DATA_SIZE=+80%FREE, then we will automatically consume
80% of free space in volume group upon restart of service.
If user did not specify DATA_SIZE, then by default script determines data
volume size to be 98% of free space in volume group. And we got rid of that
logic to auto extend. This is very similar, difference is that was default
and this is user specified.
Now if we are moving towrads relying on lvm to auto grow pool based on
/etc/lvm/lvm.conf settings, then we don't require this.
Also it will make life little easier in some cases where this behavior is
unexected. For example, assume root volume group is 500G in size and I
want to use only 50% of free space then one can …

Disable auto data volume extension when DATA_SIZE is specified

---

docker-storage-setup.1
docker-storage-setup.conf
docker-storage-setup.sh
docker-storage-setup.spec

Fixes #24 
This is generic cleanup related to growpart utility and logic around it. I think for project atomic one shall have to take care of two things.
- Make sure that cloud-utils-growpart gets installed. Installing docker-storage-setup will not pull it in automatically.
- Make sure to modify GROWPART= variable in /etc/sysconfig/docker-storage-setup to enable automatic growing of root pvs each reboot.

Disable growpart logic by default

---

docker-storage-setup.sh

Fixes issue #26 
Right now docker-storage-setup creates storage options which are valid
only for devicemapper driver. If some other driver is trying to initialize
and it is not properly written it will return error saying unrecognized
options dm.fs etc.
I am running into this issue now. Recently upstream has added zfs as
graphdriver and that takes precedence over devicemapper. And that driver
is returning error that dm.fs is unrecognized option.
Given that docker-storage-setup is expecting docker to use devicemapper
graphdriver and generating options which only work with devicemapper,
it makes sense to enforce the driver to use here to avoid errors.

docker-storage-setup: Enforce storage driver to be devicemapper

---

docker-storage-setup.1
docker-storage-setup.conf
docker-storage-setup.sh

Fixes #32 
Right now by default we reserve 98% of free space as data volume. Now we
have enabled automatic pool extension logic. That will make sure that pool
data and metadata volumes will grow automatically as they start filling up.
This means we don't have to consume all the free space available at startup.
It can be consumed dynamically. One advantage of not consuming all the space
up front is that it can be used for some other purpose. For example, one
can try to grow root volume. 3G of root might not be sufficient.
Leaving free space also allows for extension of metadata volume later easily.
Some openshift folks complained that not enough metadata size is being
reserved at startup time. Leaving space free and growing volumes dynamically
gives us lot of flexibility here for different …

docker-storage-setup: Reserve 60% of free space for data volume

---

docker-storage-setup.1
docker-storage-setup.conf
docker-storage-setup.sh

Fixes #31 and #23 
This patch does two things.
- Provides a knob CHUNK_SIZE to allow controlling chunk size of thin pool.
- Switches to default chunk size of 512K instead of 64K default of lvm.
Setting a chunk size is very tricky. larger chunk size can help in reducing
metadata usage and fragmentation. But at the same time consume more disk
space.
This chunk size has been arrived based on jeremy's testing and recommendation
from thin pool developers.
In case this does not work well, we can always change default.

docker-storage-setup: Use chunk size 512K by default

---

docker-storage-setup.sh

Otherwise we end up polluting `/` on a mainline system, and on Atomic
it will fail.

Create temporary files in /tmp, not cwd

---

docker-storage-setup.sh

Fixes #39 
It can happen that we created a metadata volume and later there was not
enough space to create data volume and script exited, leaving behind
metadata volume. Later if user adds more space to volume group and re-runs
the script, it fails saying metadata volume already exists.
For now fix this by checking if metadata volume exists or not. If it exists
use it (instead of erroring out).
I think ideally we should have cleanup logic and cleanup any logical
volumes created if error happens later. That probably also means
getting rid of "set -e".

docker-storage-setup: If metadata volume already exists, do not create new one

---

docker-storage-setup.sh

When one allocates more space, one expects to be able to use it.
Closes #7

Grow root filesystem when growing LV

---

docker-storage-setup.1
docker-storage-setup.sh

Fixes #51 
Add an option -h to display help message. Somebody got surprised when they
typed "docker-storage-setup -h" and it went ahead and setup the storage.

docker-storage-setup: Add an option -h for help message

---

docker-storage-setup.sh

Fixes issue #56 
lvcreate creates data and metadata volumes before they are converted in
thin pool volume. If lvcreate finds an existing signature, it asks the
question whether to wipe it or not. As we run as a service by default
answer is no. But that signature gets wiped out anyway. Reason being
that lvcreate zeroes first 4K of logical volume and as part of that
zeroing any signatures in first 4K will get wiped out.
IOW, as of now, it does not matter what's the answer. We are wiping out
signatures by default during lvcreate.
And there are following messages on console.
docker-storage-setup[3240]: WARNING: xfs signature detected on /dev/rhel/docker-pool at offset 0. Wipe it? [y/n]: n
docker-storage-setup[3240]: Aborted wiping of xfs.
docker-storage-setup[3240]: 1 existing signature left …

docker-storage-setup: Use option -y for lvcreate

---

docker-storage-setup.1
docker-storage-setup.conf

Fixes issue #67 
Some people complained that using 60% of free space might be a lot. Instead
start small and let the pool grow automatically. 
So drop the default data volume size to 40% of free space.

docker-storage-setup: Default to using 40% of free space for data volume

---

docker-storage-setup.sh
libdss.sh

Fixes issue #70 
Previously we were not doing any checks on DATA_SIZE suffixes and passing
everything to lvm directly. It turns out lvm just checks if things are
starting with valid suffix and anythign after that is acceptable. For
example -L 5GHello is acceptable and lvm will treat it as 5GiB.
Then with MIN_DATA_SIZE patch, we put limitations on suffixes. One could
use only one valid suffix character and nothing after that. For example,
only 5G is acceptable and 5GB and 5GiB are failing.
This is being seen as regression.
This patch allows now [bB] and i[bB] after the valid suffix. That is,
values of type 5G, 5GB, 5GiB are acceptable and all will be treated
as 5GiB.

docker-storage-setup: Relax restriction on data size suffixes

---

docker-storage-setup.sh

Fixes issue #78 
Right now if user wants to grow partitions and specifies GROWPART=true then
d-s-s will not fail even if /usr/bin/growpart is not available.
Hence, give an error message and exit is /usr/bin/growpart is not available
and user specified GROWPART=true.

docker-storage-setup: Error out if /usr/bin/growpart is not available

---

docker-storage-setup.sh

This line would have failed as soon as Docker `2.0` was released. Also de-quoted for numeric comparison (keeps consistent with rest of file)

Correct version check for Docker > 1.7

---

docker-storage-setup.sh

Docker 1.9 has now deferred device deletion feature support for devicemapper. That means a container can be removed even if underlying device is busy as it has leaked into another mount namespaces. We are having issues where a container is launched and then SPC is launched and root device of containers launched before SPC leaks into SPC container under /hosts. That means none of the container launched before SPC can be deleted till SPC exits.
This should help fix that issue.

Enable deferred device deletion feature for devicemapper

---

docker-storage-setup.sh

Right now we are checking early that either rootfs is backed by a volume group or user has specified a volume group using VG=. Otherwise script exits early thinking no progress can be made.
This was true when we only supported devicemapper storage driver. Now we also support overlay and overlay can still be configured even if a valid VG is not there.
Fix it.

Allow overlay to be used even if image is not using lvm

---

docker-storage-setup.sh

Set VG_EXISTS=1 after volume group creation. Later code checks it to
make sure volume group exists otherwise code errors out.

Set VG_EXISTS=1 after volume group creation

---

docker-storage-setup.sh

Multiple authors/contributors had left the script with
inconsistent indentation which made the code harder
to read.

Clean up indentation in docker-storage-setup.sh

---

docker-storage-setup.sh

Quotes around `DOCKER_STORAGE_OPTIONS` are required for an init script which does `source /etc/sysconfig/docker-storage`.

Add quotes around generated DOCKER_STORAGE_OPTIONS

---

docker-storage-setup.sh

Variable name should be needs_partitioned instead of need_partitioned.

Fix needs_partitioned variable name

---

docker-storage-setup.sh
libdss.sh

Right now one can pass in any xyz string in DEVS= and there are no error
checks and sfdisk tries to partition it and fails with odd error messages
like as follows.
INFO: Volume group backing root filesystem could not be determined
./docker-storage-setup.sh: line 463: * 2 - 2048 : syntax error: operand expected (error token is "* 2 - 2048 ")
ERROR: No valid volume group found. Exiting.
Instead check for valid block devices early and fail gracefully.

Make sure passed in block devices are valid block devices

---

docker-storage-setup.sh

Looks like we allow just block device name as valid input. Say DEVS=sda.
Recent changes broke it as it expected input to be a full device path
name (/dev/sda). 
For now fix it by continuing to accept just device name as input and
prefix /dev/ internally. 

Allow block device name as valid input to DEVS

---

libdss.sh

docker-storage-setup.sh functions expect to return strings via STDOUT 
therefore Info() cannot report messages on that FD.
This patch moves Info() messages to STDERR.
Signed-off-by: Jhon Honce <jhonce@redhat.com>

Move Info() messages to STDERR

---

tests/run-tests.sh

Right now run-tests.sh exits with success even if a test failed. Fix it.

Fix exit code of run-tests.sh

---

docker-storage-setup.sh

Fixes #99 
Right now we have very crude logic to figure out if a device is partition
or not. It fails on some devices whose names end with a number. Use lsblk
instead to figure out if a device is partition or not.

use lsblk to figure out if a device is partition or not

---

docker-storage-setup.1
docker-storage-setup.conf
docker-storage-setup.sh

We're seeing some [bad behavior](https://github.com/docker/docker/issues/20707) when xfs is used and the underlying LV/VG/PV are completely full.  Experimentally, ext4 has better failure modes, so this commit allows setting the filesystem.

Allow dm.fs to be overridden

---

docker-storage-setup.1
docker-storage-setup.conf
docker-storage-setup.sh

Introduce an helper to wait for a device. Also make wait time configurable
using knob DEVICE_WAIT_TIMEOUT. Default value is 60 seconds. One can disable
wait by specifying DEVICE_WAIT_TIMEOUT=0.

Introduce a helper to wait for a device

---

docker-storage-setup.sh

Fixes #112 
Thin pool wait can timeout for two reasons. First one is that thin pool
exists but it is taking longer to activate and second one is that thin
pool does not exist any more (user has deleted the thin pool but did not
remove /etc/sysconfig/docker-storage).
Current error message covers the first condition but does not say anything
about second possibility.
Improve error message so that a user can take appropriate action.

Improve error message when thin pool wait times out

---

docker-storage-setup.sh

If a user has not specified `-g` or `--graph` for $DOCKER_ROOT_DIR
in `/etc/sysconfig/docker`, then $DOCKER_ROOT_DIR will default to
`/var/lib/docker`. In that case, $path will be empty, and `realpath`
would fail. This PR addresses that issue.
Signed-off-by: Shishir Mahajan <shishir.mahajan@redhat.com>

get_docker_root_dir: use realpath only when path is not empty.

---

container-storage-setup.sh

Bumped version from 0.3.0 to 0.6.0. I realized that in the past we already
released some versions like v0.5. So to avoid conflict with previous versions
bump it to a higher number which has never been released.

Release version 0.6.0
